# Generated by Django 5.1.2 on 2024-10-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url_to_brand_page',
        ),
    ]
